require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PrefixGroupsController do

  # This should return the minimal set of attributes required to create a valid
  # PrefixGroup. As you add validations to PrefixGroup, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PrefixGroupsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all prefix_groups as @prefix_groups" do
      prefix_group = PrefixGroup.create! valid_attributes
      get :index, {}, valid_session
      assigns(:prefix_groups).should eq([prefix_group])
    end
  end

  describe "GET show" do
    it "assigns the requested prefix_group as @prefix_group" do
      prefix_group = PrefixGroup.create! valid_attributes
      get :show, {:id => prefix_group.to_param}, valid_session
      assigns(:prefix_group).should eq(prefix_group)
    end
  end

  describe "GET new" do
    it "assigns a new prefix_group as @prefix_group" do
      get :new, {}, valid_session
      assigns(:prefix_group).should be_a_new(PrefixGroup)
    end
  end

  describe "GET edit" do
    it "assigns the requested prefix_group as @prefix_group" do
      prefix_group = PrefixGroup.create! valid_attributes
      get :edit, {:id => prefix_group.to_param}, valid_session
      assigns(:prefix_group).should eq(prefix_group)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PrefixGroup" do
        expect {
          post :create, {:prefix_group => valid_attributes}, valid_session
        }.to change(PrefixGroup, :count).by(1)
      end

      it "assigns a newly created prefix_group as @prefix_group" do
        post :create, {:prefix_group => valid_attributes}, valid_session
        assigns(:prefix_group).should be_a(PrefixGroup)
        assigns(:prefix_group).should be_persisted
      end

      it "redirects to the created prefix_group" do
        post :create, {:prefix_group => valid_attributes}, valid_session
        response.should redirect_to(PrefixGroup.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved prefix_group as @prefix_group" do
        # Trigger the behavior that occurs when invalid params are submitted
        PrefixGroup.any_instance.stub(:save).and_return(false)
        post :create, {:prefix_group => {}}, valid_session
        assigns(:prefix_group).should be_a_new(PrefixGroup)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PrefixGroup.any_instance.stub(:save).and_return(false)
        post :create, {:prefix_group => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested prefix_group" do
        prefix_group = PrefixGroup.create! valid_attributes
        # Assuming there are no other prefix_groups in the database, this
        # specifies that the PrefixGroup created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PrefixGroup.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => prefix_group.to_param, :prefix_group => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested prefix_group as @prefix_group" do
        prefix_group = PrefixGroup.create! valid_attributes
        put :update, {:id => prefix_group.to_param, :prefix_group => valid_attributes}, valid_session
        assigns(:prefix_group).should eq(prefix_group)
      end

      it "redirects to the prefix_group" do
        prefix_group = PrefixGroup.create! valid_attributes
        put :update, {:id => prefix_group.to_param, :prefix_group => valid_attributes}, valid_session
        response.should redirect_to(prefix_group)
      end
    end

    describe "with invalid params" do
      it "assigns the prefix_group as @prefix_group" do
        prefix_group = PrefixGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PrefixGroup.any_instance.stub(:save).and_return(false)
        put :update, {:id => prefix_group.to_param, :prefix_group => {}}, valid_session
        assigns(:prefix_group).should eq(prefix_group)
      end

      it "re-renders the 'edit' template" do
        prefix_group = PrefixGroup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PrefixGroup.any_instance.stub(:save).and_return(false)
        put :update, {:id => prefix_group.to_param, :prefix_group => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested prefix_group" do
      prefix_group = PrefixGroup.create! valid_attributes
      expect {
        delete :destroy, {:id => prefix_group.to_param}, valid_session
      }.to change(PrefixGroup, :count).by(-1)
    end

    it "redirects to the prefix_groups list" do
      prefix_group = PrefixGroup.create! valid_attributes
      delete :destroy, {:id => prefix_group.to_param}, valid_session
      response.should redirect_to(prefix_groups_url)
    end
  end

end
