require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PrefixGroupsForProviderController do

  # This should return the minimal set of attributes required to create a valid
  # PrefixGroupsForProvider. As you add validations to PrefixGroupsForProvider, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PrefixGroupsForProviderController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all prefix_groups_for_provider as @prefix_groups_for_provider" do
      prefix_groups_for_provider = PrefixGroupsForProvider.create! valid_attributes
      get :index, {}, valid_session
      assigns(:prefix_groups_for_provider).should eq([prefix_groups_for_provider])
    end
  end

  describe "GET show" do
    it "assigns the requested prefix_groups_for_provider as @prefix_groups_for_provider" do
      prefix_groups_for_provider = PrefixGroupsForProvider.create! valid_attributes
      get :show, {:id => prefix_groups_for_provider.to_param}, valid_session
      assigns(:prefix_groups_for_provider).should eq(prefix_groups_for_provider)
    end
  end

  describe "GET new" do
    it "assigns a new prefix_groups_for_provider as @prefix_groups_for_provider" do
      get :new, {}, valid_session
      assigns(:prefix_groups_for_provider).should be_a_new(PrefixGroupsForProvider)
    end
  end

  describe "GET edit" do
    it "assigns the requested prefix_groups_for_provider as @prefix_groups_for_provider" do
      prefix_groups_for_provider = PrefixGroupsForProvider.create! valid_attributes
      get :edit, {:id => prefix_groups_for_provider.to_param}, valid_session
      assigns(:prefix_groups_for_provider).should eq(prefix_groups_for_provider)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PrefixGroupsForProvider" do
        expect {
          post :create, {:prefix_groups_for_provider => valid_attributes}, valid_session
        }.to change(PrefixGroupsForProvider, :count).by(1)
      end

      it "assigns a newly created prefix_groups_for_provider as @prefix_groups_for_provider" do
        post :create, {:prefix_groups_for_provider => valid_attributes}, valid_session
        assigns(:prefix_groups_for_provider).should be_a(PrefixGroupsForProvider)
        assigns(:prefix_groups_for_provider).should be_persisted
      end

      it "redirects to the created prefix_groups_for_provider" do
        post :create, {:prefix_groups_for_provider => valid_attributes}, valid_session
        response.should redirect_to(PrefixGroupsForProvider.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved prefix_groups_for_provider as @prefix_groups_for_provider" do
        # Trigger the behavior that occurs when invalid params are submitted
        PrefixGroupsForProvider.any_instance.stub(:save).and_return(false)
        post :create, {:prefix_groups_for_provider => {}}, valid_session
        assigns(:prefix_groups_for_provider).should be_a_new(PrefixGroupsForProvider)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PrefixGroupsForProvider.any_instance.stub(:save).and_return(false)
        post :create, {:prefix_groups_for_provider => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested prefix_groups_for_provider" do
        prefix_groups_for_provider = PrefixGroupsForProvider.create! valid_attributes
        # Assuming there are no other prefix_groups_for_provider in the database, this
        # specifies that the PrefixGroupsForProvider created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PrefixGroupsForProvider.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => prefix_groups_for_provider.to_param, :prefix_groups_for_provider => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested prefix_groups_for_provider as @prefix_groups_for_provider" do
        prefix_groups_for_provider = PrefixGroupsForProvider.create! valid_attributes
        put :update, {:id => prefix_groups_for_provider.to_param, :prefix_groups_for_provider => valid_attributes}, valid_session
        assigns(:prefix_groups_for_provider).should eq(prefix_groups_for_provider)
      end

      it "redirects to the prefix_groups_for_provider" do
        prefix_groups_for_provider = PrefixGroupsForProvider.create! valid_attributes
        put :update, {:id => prefix_groups_for_provider.to_param, :prefix_groups_for_provider => valid_attributes}, valid_session
        response.should redirect_to(prefix_groups_for_provider)
      end
    end

    describe "with invalid params" do
      it "assigns the prefix_groups_for_provider as @prefix_groups_for_provider" do
        prefix_groups_for_provider = PrefixGroupsForProvider.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PrefixGroupsForProvider.any_instance.stub(:save).and_return(false)
        put :update, {:id => prefix_groups_for_provider.to_param, :prefix_groups_for_provider => {}}, valid_session
        assigns(:prefix_groups_for_provider).should eq(prefix_groups_for_provider)
      end

      it "re-renders the 'edit' template" do
        prefix_groups_for_provider = PrefixGroupsForProvider.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PrefixGroupsForProvider.any_instance.stub(:save).and_return(false)
        put :update, {:id => prefix_groups_for_provider.to_param, :prefix_groups_for_provider => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested prefix_groups_for_provider" do
      prefix_groups_for_provider = PrefixGroupsForProvider.create! valid_attributes
      expect {
        delete :destroy, {:id => prefix_groups_for_provider.to_param}, valid_session
      }.to change(PrefixGroupsForProvider, :count).by(-1)
    end

    it "redirects to the prefix_groups_for_provider list" do
      prefix_groups_for_provider = PrefixGroupsForProvider.create! valid_attributes
      delete :destroy, {:id => prefix_groups_for_provider.to_param}, valid_session
      response.should redirect_to(prefix_groups_for_providers_url)
    end
  end

end
